### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Repentz** [Qbox-project/qb-storerobbery#4]
All you need to do is cancel the robbery animation mid lockpick whilst getting money before it ends. Then re-lockpick it and repeat.

**Comment by iiKline** [comment]
Bug to get unlimited money in registers with no cooldown*

**Comment by Repentz** [comment]
I suggest using marked bills upon completion if possible.

**Comment by ChatDisabled** [comment]
> I suggest using marked bills upon completion if possible.

I don't see how bills that are in the register. Which the store only got that day are somehow counted and trackable by the government. It was always just straight cash and also makes it more profitable for RP'ers. More realistic if you only get marked bills out of the safes. Money actually counted for and _safed_.

Anyway easy fix but currently working on [qb-jewelery](https://github.com/QBCore-Remastered/qb-jewelery)

**Comment by Manason** [comment]
I'm guessing the original idea behind marked bills was to have money as an item so that police stopping you could search and confiscate the stolen cash. Would probably be better in general if money on your person didn't have any special handling, but was simply a stackable item. It needs the same functionality of trading, giving, etc as other items.

**Comment by ChatDisabled** [comment]
> I'm guessing the original idea behind marked bills was to have money as an item so that police stopping you could search and confiscate the stolen cash. Would probably be better in general if money on your person didn't have any special handling, but was simply a stackable item. It needs the same functionality of trading, giving, etc as other items.

Original functionality was that if someone holds more than x amount of cash. They can confiscate it because the police has a command for it. Marked bills is unrelated to this and always considerd _illegal_.

Issue should be fixed with https://github.com/Qbox-project/qb-storerobbery/commit/3b35841c75c2645dac97b7a9495751ab4712dda6
